# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv('cars1.csv')
cars2 = pd.read_csv('cars2.csv')

### Step 4. Ops it seems our first dataset has some unnamed blank columns, fix cars1

In [6]:
cars1 = cars1.loc[:, "mpg":"car"]

### Step 5. What is the number of observations in each dataset?

In [8]:
print(cars1.shape[0])
print(cars2.shape[0])

198
200

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [12]:
cars = pd.concat([cars1, cars2])

### Step 7. Ops there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [21]:
owners = np.random.randint(15000, 73000, size = len(cars))
owners

array([46815, 59319, 63969, 72186, 16737, 16062, 25345, 64703, 66942,
       36791, 19577, 38977, 72918, 65344, 15846, 68701, 60101, 53975,
       24782, 16257, 26714, 27135, 54396, 30426, 42701, 49677, 46208,
       24950, 24882, 28974, 40492, 33250, 57310, 52524, 61372, 55087,
       45362, 20216, 61932, 68253, 71467, 47074, 47988, 25493, 16304,
       68155, 65255, 66769, 36872, 34443, 30973, 39312, 58325, 55977,
       69641, 33535, 41139, 50837, 30503, 30497, 54029, 21259, 71136,
       51634, 29860, 63400, 30813, 53470, 62703, 58805, 34040, 38739,
       39155, 21998, 60036, 64198, 62290, 18679, 22287, 59497, 44752,
       42324, 50531, 68035, 44300, 48813, 53259, 43791, 54321, 44556,
       24741, 27175, 63876, 65884, 53448, 16456, 72166, 31549, 53383,
       31754, 40477, 34503, 41714, 62091, 31351, 31059, 17335, 36948,
       43182, 57279, 22050, 41150, 32871, 22953, 24529, 50700, 54182,
       51038, 19124, 45064, 40288, 49197, 70816, 70154, 42298, 39400,
       32769, 16400, 42565, 66127, 27438, 39264, 57575, 51237, 72629,
       40454, 72941, 48465, 68932, 16305, 27689, 50142, 59557, 50016,
       35631, 68835, 28966, 57068, 67640, 29120, 57695, 41495, 23482,
       32168, 35255, 43012, 71641, 55276, 29058, 60081, 63775, 22720,
       19458, 66065, 56752, 52332, 63692, 38680, 49822, 62640, 54099,
       70292, 25825, 51418, 31637, 21731, 28398, 51741, 42959, 55745,
       43518, 51381, 16878, 53800, 48058, 57753, 64345, 60714, 71890,
       24618, 48507, 40447, 63102, 47229, 64646, 23011, 24302, 23180,
       21190, 17424, 16399, 19136, 53434, 39437, 60104, 40595, 60152,
       57465, 32866, 18310, 65941, 40752, 38021, 72242, 70169, 45261,
       16465, 68678, 37604, 47732, 28849, 66173, 48221, 54483, 52455,
       63048, 51278, 55605, 34476, 55783, 54051, 19720, 23395, 69731,
       68627, 33379, 38028, 55486, 27393, 40206, 47045, 20123, 43626,
       35385, 23707, 43335, 19840, 20307, 16445, 64022, 48633, 35249,
       17075, 52827, 54074, 43410, 63154, 56329, 25091, 53881, 38101,
       55035, 44657, 69561, 24900, 41665, 17905, 44629, 21976, 35708,
       55662, 19516, 57283, 66951, 22627, 53119, 31048, 51591, 32392,
       53971, 20271, 22032, 30251, 53255, 56600, 16672, 34604, 16659,
       22705, 59283, 49477, 32108, 23888, 33079, 36578, 37163, 34793,
       63725, 16010, 45396, 61002, 26902, 21410, 64217, 49326, 42270,
       24644, 37542, 15488, 19472, 17899, 20853, 24920, 56643, 22382,
       55113, 24025, 38326, 68381, 70568, 24890, 61370, 55898, 54370,
       62681, 21570, 64480, 72668, 18923, 28429, 53370, 25196, 17860,
       36089, 17313, 18722, 16981, 52643, 35523, 23710, 60154, 42693,
       54466, 20386, 37045, 64133, 43238, 52425, 64461, 56499, 29278,
       59367, 67856, 32618, 70236, 37159, 44156, 70795, 55558, 18579,
       71063, 35854, 64804, 48339, 34660, 60283, 51084, 69759, 59912,
       55050, 22665, 44092, 50611, 52650, 32053, 71644, 32466, 32957,
       52888, 66910, 49294, 56031, 45640, 51508, 65937, 53838, 66236,
       44955, 53006, 61113, 65281, 22039, 47725, 35419, 64759, 60446,
       59962, 61594])

### Step 8. Add the column owners to cars

In [22]:
cars['owners'] = owners
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,46815
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,59319
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,63969
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,72186
4,17.0,8,302,140,3449,10.5,70,1,ford torino,16737
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,16062
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,25345
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,64703
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,66942
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,36791
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,19577
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,38977
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,72918
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),65344
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,15846
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,68701
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,60101
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,53975
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,24782
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,16257
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,26714
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,27135
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,54396
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,30426
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,42701
25,10.0,8,360,215,4615,14.0,70,1,ford f250,49677
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,46208
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,24950
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,24882
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,28974
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,59912
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,55050
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,22665
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,44092
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,50611
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,52650
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,32053
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,71644
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,32466
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,32957
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,52888
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,66910
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,49294
183,36.0,4,107,75,2205,14.5,82,3,honda accord,56031
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,45640
185,38.0,4,91,67,1965,15.0,82,3,honda civic,51508
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),65937
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,53838
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,66236
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),44955
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,53006
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,61113
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,65281
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,22039
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,47725
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,35419
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,64759
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,60446
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,59962
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,61594